### ISSUE TITLE
Unknown blueprint: ember-cli-rx

### ISSUE THREAD

**Issue by gnapse** [blesh/ember-cli-rx#1] opened 2015-02-06 15:40 UTC
I followed the install instructions in the README, and on the second comand I get an error:

```
$ npm install --save-dev ember-cli-rx
ember-cli-rx@0.0.0 node_modules/ember-cli-rx

$ ember generate ember-cli-rx
version: 0.1.6
Unknown blueprint: ember-cli-rx
```

Any comments on that?

**Comment by machty** [comment] 2015-04-04 14:08
@gnapse we still need to publish everything to npm, but if you use master are you still getting this error? I can't reproduce.

**Comment by benlesh** [comment] 2015-04-07 17:56
poke @gnapse ... I also couldn't get this to reproduce. Perhaps it was a bad npm install?

**Comment by jayphelps** [comment] 2015-04-07 17:59
This was related to it being `0.0.0`. Fixed now that we're cutting proper releases.

**Comment by benlesh** [comment] 2015-04-07 20:15
Okay, closing this then.

**Closed as completed by benlesh** 2015-04-07 20:15 UTC
